// MySQL 4.1.x
// Benutzer anlegen und Rechte für die DB zuteilen
// Benutzer "press" und passwort "mypresspass"
GRANT CREATE TEMPORARY TABLES ON * . * TO 'press'@'localhost' IDENTIFIED BY PASSWORD '*8E6E04D9EAFC5C37FBA8C0500E4B3A994B649DFC' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;
GRANT SELECT , INSERT ,UPDATE ,DELETE ,CREATE ,DROP ,INDEX ,ALTER ,CREATE TEMPORARY TABLES ON `presse` . * TO press@localhost;