<?php
$table_definition_['main'] =
array (
  0 => 
  array (
    0 => 'id',
    'Field' => 'id',
    1 => 'int(6)',
    'Type' => 'int(6)',
    2 => '',
    'Null' => '',
    3 => 'PRI',
    'Key' => 'PRI',
    4 => NULL,
    'Default' => NULL,
    5 => 'auto_increment',
    'Extra' => 'auto_increment',
  ),
  1 => 
  array (
    0 => 'name',
    'Field' => 'name',
    1 => 'varchar(200)',
    'Type' => 'varchar(200)',
    2 => '',
    'Null' => '',
    3 => 'MUL',
    'Key' => 'MUL',
    4 => '',
    'Default' => '',
    5 => '',
    'Extra' => '',
  ),
  2 => 
  array (
    0 => 'vorname',
    'Field' => 'vorname',
    1 => 'varchar(200)',
    'Type' => 'varchar(200)',
    2 => '',
    'Null' => '',
    3 => '',
    'Key' => '',
    4 => '',
    'Default' => '',
    5 => '',
    'Extra' => '',
  ),
  3 => 
  array (
    0 => 'strasse',
    'Field' => 'strasse',
    1 => 'varchar(200)',
    'Type' => 'varchar(200)',
    2 => '',
    'Null' => '',
    3 => '',
    'Key' => '',
    4 => '',
    'Default' => '',
    5 => '',
    'Extra' => '',
  ),
  4 => 
  array (
    0 => 'plz',
    'Field' => 'plz',
    1 => 'varchar(7)',
    'Type' => 'varchar(7)',
    2 => '',
    'Null' => '',
    3 => '',
    'Key' => '',
    4 => '',
    'Default' => '',
    5 => '',
    'Extra' => '',
  ),
  5 => 
  array (
    0 => 'ort',
    'Field' => 'ort',
    1 => 'varchar(200)',
    'Type' => 'varchar(200)',
    2 => '',
    'Null' => '',
    3 => '',
    'Key' => '',
    4 => '',
    'Default' => '',
    5 => '',
    'Extra' => '',
  ),
  6 => 
  array (
    0 => 'vw',
    'Field' => 'vw',
    1 => 'varchar(7)',
    'Type' => 'varchar(7)',
    2 => '',
    'Null' => '',
    3 => '',
    'Key' => '',
    4 => '',
    'Default' => '',
    5 => '',
    'Extra' => '',
  ),
  7 => 
  array (
    0 => 'tel',
    'Field' => 'tel',
    1 => 'varchar(15)',
    'Type' => 'varchar(15)',
    2 => '',
    'Null' => '',
    3 => '',
    'Key' => '',
    4 => '',
    'Default' => '',
    5 => '',
    'Extra' => '',
  ),
  8 => 
  array (
    0 => 'email',
    'Field' => 'email',
    1 => 'varchar(200)',
    'Type' => 'varchar(200)',
    2 => '',
    'Null' => '',
    3 => '',
    'Key' => '',
    4 => '',
    'Default' => '',
    5 => '',
    'Extra' => '',
  ),
  9 => 
  array (
    0 => 'confirm',
    'Field' => 'confirm',
    1 => 'varchar(32)',
    'Type' => 'varchar(32)',
    2 => '',
    'Null' => '',
    3 => '',
    'Key' => '',
    4 => '',
    'Default' => '',
    5 => '',
    'Extra' => '',
  ),
);
?>
